-----------------------------------------
-- Jeremy Magee, 2016 March 2 --
-- Create MEMBER, MEMBER_TYPE, and DUES_PAYMENT tables --
-----------------------------------------

CREATE TABLE `FSSA`.`MEMBER` (
  `MEMBER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `MIDDLENAME` VARCHAR(45) NULL,
  `BIRTHDATE` DATETIME NOT NULL,
  `BIRTHPLACE` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(100) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `PROVINCE` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `POSTALCODE` VARCHAR(6) NOT NULL,
  `HOME_PHONE` VARCHAR(11) NOT NULL,
  `CELL_PHONE` VARCHAR(11) NULL,
  `EMAIL_ADDRESS` VARCHAR(70) NULL,
  `MEMBER_TYPE` VARCHAR(45) NOT NULL,
  `DATE_APPLIED` DATETIME NULL,
  `DATE_APPROVED` DATETIME NULL,
  `DATE_INDUCTED` DATETIME NULL,
  `USER_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MEMBER_ID`));

CREATE TABLE `FSSA`.`MEMBER_TYPE` (
  `MEMBER_TYPE_ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(100) NOT NULL,
  `DURATION` INT NOT NULL,
  PRIMARY KEY (`MEMBER_TYPE_ID`));

CREATE TABLE `FSSA`.`DUES_PAYMENT` (
  `DUES_PAYMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `MEMBER_ID` INT NOT NULL,
  `RENEWED_MEMBER_TYPE` INT NOT NULL,
  `PAYMENT_AMOUNT` DECIMAL NOT NULL,
  `DATE_RENEWED` DATETIME NOT NULL,
  `RENEWAL_EXPIRY_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`DUES_PAYMENT_ID`),
  INDEX `fk_DUES_PAYMENT_MEMBER_idx` (`MEMBER_ID` ASC),
  INDEX `fk_DUES_PAYMENT_1_idx` (`RENEWED_MEMBER_TYPE` ASC),
  CONSTRAINT `FK_DUES_PAYMENT_MEMBER`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `FSSA`.`MEMBER` (`MEMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DUES_PAYMENT_MEMBER_TYPE`
    FOREIGN KEY (`RENEWED_MEMBER_TYPE`)
    REFERENCES `FSSA`.`MEMBER_TYPE` (`MEMBER_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
